version: '3.8'

services:
  netbox: &a1
    image: docker.io/netboxcommunity/netbox:${VERSION-v4.0-2.9.1}
    depends_on:
      - postgres
      - redis
      - redis-cache
    env_file: env/netbox.env
    user: unit:root
    healthcheck:
      start_period: 60s
      timeout: 3s
      interval: 15s
      test: curl -f http://localhost:8080/login/ || exit 1
    volumes:
      - ./configuration:/etc/netbox/config:z,ro
      - ./netbox-media-files:/opt/netbox/netbox/media:rw
      - ./netbox-reports-files:/opt/netbox/netbox/reports:rw
      - ./netbox-scripts-files:/opt/netbox/netbox/scripts:rw
    restart: unless-stopped

  netbox-worker:
    <<: *a1
    depends_on:
      netbox:
        condition: service_healthy
    command:
      - /opt/netbox/venv/bin/python
      - /opt/netbox/netbox/manage.py
      - rqworker
    healthcheck:
      start_period: 20s
      timeout: 3s
      interval: 15s
      test: ps -aux | grep -v grep | grep -q rqworker || exit 1
    restart: unless-stopped

  netbox-housekeeping:
    <<: *a1
    depends_on:
      netbox:
        condition: service_healthy
    command:
      - /opt/netbox/housekeeping.sh
    healthcheck:
      start_period: 20s
      timeout: 3s
      interval: 15s
      test: ps -aux | grep -v grep | grep -q housekeeping || exit 1
    restart: unless-stopped

  postgres:
    image: docker.io/postgres:16-alpine
    env_file: env/postgres.env
    volumes:
      - ./netbox-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: docker.io/redis:7-alpine
    command:
      - sh
      - -c
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD
    env_file: env/redis.env
    volumes:
      - ./netbox-redis-data:/data
    restart: unless-stopped

  redis-cache:
    image: docker.io/redis:7-alpine
    command:
      - sh
      - -c
      - redis-server --requirepass $$REDIS_PASSWORD
    env_file: env/redis-cache.env
    volumes:
      - ./netbox-redis-cache-data:/data
    restart: unless-stopped

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx_netbox
    ports:
      - 445:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro

  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - /run/user/1005/docker.sock:/var/run/docker.sock
      - ./diun:/diun # Path to store Diun's data
    environment:
      - "TZ=Europe/Ljubljana"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_NOTIF_MAIL_HOST=smtp.gmail.com"
      - "DIUN_NOTIF_MAIL_PORT=587"
      - "DIUN_NOTIF_MAIL_SSL=false"
      - "DIUN_NOTIF_MAIL_LOCALNAME=xxx"
      - "DIUN_NOTIF_MAIL_USERNAME=xxx@gmail.com"
      - "DIUN_NOTIF_MAIL_PASSWORD=xxx"
      - "DIUN_NOTIF_MAIL_FROM=rxxx@gmail.com"
      - "DIUN_NOTIF_MAIL_TO=xxx@gmail.com"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 * 11 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCH"
